# Generated by Django 4.1.3 on 2022-12-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fire_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=255)),
                ('fire_degree', models.CharField(choices=[('1st degree', '1ST DEGREE'), ('2nd degree', '2ND DEGREE'), ('3rd degree', '3RD DEGREE')], max_length=11)),
                ('fire_departments', models.CharField(choices=[('class a', 'CLASS A'), ('class b', 'CLASS B'), ('class c', 'CLASS C'), ('class d', 'CLASS D'), ('class e', 'CLASS E')], max_length=10)),
                ('No_of_tanks', models.PositiveIntegerField()),
                ('water_hoses', models.PositiveIntegerField()),
                ('comments', models.TextField()),
                ('date_time_started', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
